[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\adchurch\archive\addons\veristand steps for teststand'

[projects.runtime]
path = 'Source\LV\RunTime\VeriStand Steps RunTime Library.lvproj'

[projects.installer]
path = 'Source\LV\Installer\Installer.lvproj'

[[codegen.steps]]
name = 'Update Project Files'
type = 'lvUpdateProjectFiles'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL'
type = 'lvBuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[test]
sequence_path = 'Tests\Base Test Files\Main.seq'
teststand_version = '2014'
