[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\NIVeriStandAdd-ons\archive\addons\veristand steps for teststand'

[projects.runtime]
path = 'Source\LV\RunTime\VeriStand Steps RunTime Library.lvproj'

[projects.installer]
path = 'Source\LV\Installer\Installer.lvproj'

[[codegen.steps]]
name = 'Update Project Files'
type = 'lvUpdateProjectFiles'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL'
type = 'lvBuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[test.steps]]
name = 'Integration Test'
type = 'Test'
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2014'

[package]
type = 'vsStepsPackage'
types_version = '7.2.2'
teststand_versions = ['2014','2016','2017']

[test]
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2014'


