[archive]
build_output_dir = 'Source\LV\Installer\built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\archive\addons\veristand steps for teststand'

[projects.misc]
path = 'Source\LV\Misc\MiscHelperVIs.lvproj'

[projects.rtSequence]
path = 'Source\LV\RT Sequence\RTSequenceVIs.lvproj'

[projects.channels]
path = 'Source\LV\Set Channels\Set Channels.lvproj'

[projects.logger]
path = 'Source\LV\TS VS Logger\TS VS Logger.lvproj'

[projects.installer]
path = 'Source\LV\Installer\Installer.lvproj'

[[codegen.steps]]
name = 'Update Project Files'
type = 'lvUpdateProjectFiles'

[[build.steps]]
name = 'MiscHelperVIs PPL'
type = 'lvBuildSpec'
project = '{misc}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'RTSequenceVIs PPL'
type = 'lvBuildSpec'
project = '{rtSequence}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'Set Channels PPL'
type = 'lvBuildSpec'
project = '{channels}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'Logger PPL'
type = 'lvBuildSpec'
project = '{logger}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'MiscHelperVIs PPL'
type = 'lv64BuildSpec'
project = '{misc}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'RTSequenceVIs PPL'
type = 'lv64BuildSpec'
project = '{rtSequence}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'Set Channels PPL'
type = 'lv64BuildSpec'
project = '{channels}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'Logger PPL'
type = 'lv64BuildSpec'
project = '{logger}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'Post Install Action'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'Post Install Action'

[[build.steps]]
name = 'Pre Uninstall Action'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'Pre Uninstall Action'

[[build.steps]]
name = 'TestStand 2014 Installer'
type = 'lvBuildSpec'
project = '{installer}'
target = 'My Computer'
build_spec = 'TestStand 2014 Installer'
