[archive]
build_output_dir = 'Built'
archive_location = 'C:\Users\lvuser\Documents\Archive'

[projects.runtime]
path = 'Source\LV\RunTime\VeriStand Steps RunTime Library.lvproj'

[projects.installer]
path = 'Source\LV\Installer\VeriStand Steps Installer.lvproj'

[[codegen.steps]]
name = 'Update Project Files'
type = 'lvRunVi'
vi = 'Source\LV\Build\UpdateProjectFiles.vi'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL'
type = 'lvBuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'VeriStand Steps RunTime PPL x64'
type = 'lv64BuildSpec'
project = '{runtime}'
target = 'My Computer'
build_spec = 'Packed Library'

[[build.steps]]
name = 'PostInstallAction'
type = 'lvBuildSpec'
project = 'installer'
target = 'My Computer'
build_spec = 'Installer Post Install Action'

[[build.steps]]
name = 'PostInstallAction'
type = 'lvBuildSpec'
project = 'installer'
target = 'My Computer'
build_spec = 'Installer Pre Uninstall Action'

[[test.steps]]
name = 'TestStand 2017 Integration Test'
type = 'Test'
sequence_path = 'Tests\Sequences\Main.seq'
teststand_version = '2017'
teststand_bitness = '32'

[package]
type = 'vsStepsPackage'
types_version = '8.1.0'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2015_release_branches = ["master",]
2016_release_branches = ["master",]
2017_release_branches = ["master",]
2018_release_branches = ["master",]
